### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by dhruboroy29** [MukundanAtSamraksh/eMoteExt#1] opened 2018-08-19 00:26 UTC
The following is the current build error message:

`mkdir: cannot create directory 'BuildOutput/Debug/bin': No such file or directory
"../../Compilers/GCC5.4.1/bin/arm-none-eabi-ld.exe"  -static --gc-sections --no-warn-mismatch --library-path=../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/lib --library-path=../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib --allow-multiple-definition -u ARM_Vectors -u _start --Map BuildOutput/Debug/bin/tinyclr.map --output=BuildOutput/Debug/bin/tinyclr.axf --script=tinyclr_scatterfile.ldf ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/tinyclr_dat.obj ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/allocator.obj ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/tinyclr.obj -( ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/CLRStartup.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/CRC.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/CorLib.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Core.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger_extended.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger_full.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger_minimal.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Diagnostics.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Diagnostics_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Graphics_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Hardware.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Hardware_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/HeapPersistence.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/HeapPersistence_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/I2C.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/I2C_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/IOPort.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/IOPort_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/InterruptHandler.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/InterruptHandler_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Messaging.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Messaging_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/RPC.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/RPC_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_OneWire.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_PWM.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_PWM_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_SerialPort.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_SerialPort_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_Usb.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_Usb_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Messaging.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Messaging_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Serialization.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Serialization_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Update.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SecurityPkcs11.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Serialization.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Serialization_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Stream.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Stream_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/WireProtocol.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Xml.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Xml_stub.lib ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/lib/static_tinyclr.lib InteropAssembliesTable.lib  ext.lib -) -( ../../GCCLibs/GCC5.4/newlib/armv7-m/libm.a ../../GCCLibs/GCC5.4/newlib/armv7-m/libc.a ../../Compilers/GCC5.4.1/lib/gcc/arm-none-eabi/5.4.1/armv7-m/libgcc.a -) -(  -)
/bin/sh: -c: line 0: syntax error near unexpected token '('
/bin/sh: -c: line 0: '"../../Compilers/GCC5.4.1/bin/arm-none-eabi-ld.exe"  -static --gc-sections --no-warn-mismatch --library-path=../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/lib --library-path=../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib --allow-multiple-definition -u ARM_Vectors -u _start --Map BuildOutput/Debug/bin/tinyclr.map --output=BuildOutput/Debug/bin/tinyclr.axf --script=tinyclr_scatterfile.ldf ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/tinyclr_dat.obj ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/allocator.obj ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/tinyclr.obj -( ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/CLRStartup.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/CRC.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/CorLib.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Core.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger_extended.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger_full.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger_minimal.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Diagnostics.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Diagnostics_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Graphics_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Hardware.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Hardware_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/HeapPersistence.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/HeapPersistence_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/I2C.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/I2C_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/IOPort.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/IOPort_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/InterruptHandler.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/InterruptHandler_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Messaging.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Messaging_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/RPC.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/RPC_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_OneWire.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_PWM.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_PWM_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_SerialPort.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_SerialPort_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_Usb.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_Usb_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Messaging.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Messaging_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Serialization.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Serialization_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Update.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SecurityPkcs11.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Serialization.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Serialization_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Stream.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Stream_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/WireProtocol.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Xml.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Xml_stub.lib ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/lib/static_tinyclr.lib InteropAssembliesTable.lib  ext.lib -) -( ../../GCCLibs/GCC5.4/newlib/armv7-m/libm.a ../../GCCLibs/GCC5.4/newlib/armv7-m/libc.a ../../Compilers/GCC5.4.1/lib/gcc/arm-none-eabi/5.4.1/armv7-m/libgcc.a -) -(  -)'
make: *** [linker] Error 2`

**Comment by dhruboroy29** [comment] 2018-08-19 00:28
I'm using make from Mingw on Windows 10. The line `/bin/sh: -c: line 0: syntax error near unexpected token '('` seems to be the main issue here.

**Comment by mukundansridharan** [comment] 2018-08-20 15:16
The issue is that creating output directory BuildOutput/Debug/bin is failing. try running 'make clean; make outputdir', if that fails that will confirm it. Try creating the above mentioned directory manually and then run make. Not sure why mkdir is failing, its a pretty simple command.

**Comment by dhruboroy29** [comment] 2018-08-20 15:36
That's not the core issue...the fix for the build directories problem is replacing mkdir with $(MKDIR) on lines  70, 73, and 76 of the Makefile. The linker recipe seems to be failing, and there's an unexpected '(' somewhere. Could the last few characters of the linker recipe,
`... $(TOOL_DIR)/lib/gcc/arm-none-eabi/5.4.1/armv7-m/libgcc.a -) -(  -)`,
be the source of the problem?

Full error message after the mkdir fix:

`"../../Compilers/GCC5.4.1/bin/arm-none-eabi-ar.exe" -rcs ext.lib ../../Extensions/ExampleLib/Stubs/ExampleLib.obj ../../Extensions/ExampleLib/Stubs/ExampleLib_ExampleLib_Exe.obj ../../Extensions/ExampleLib/Stubs/ExampleLib_ExampleLib_Exe_mshl.obj
"../../Compilers/GCC5.4.1/bin/arm-none-eabi-g++.exe" -xc++  -Wno-invalid-offsetof -fcheck-new  -fno-threadsafe-statics    -mslow-flash-data -fdata-sections -ffunction-sections -fdollars-in-identifiers -fno-exceptions -mcpu=cortex-m3 -funsigned-char -mstructure-size-boundary=8  -DTINYCLR_ENABLE_SOURCELEVELDEBUGGING  -mthumb -DCOMPILE_THUMB2 -Wno-psabi -DVERSION_MAJOR=4 -DVERSION_MINOR=3 -DVERSION_BUILD=0 -DVERSION_REVISION=0  -DMF_VERSION="\"4.3.1.0\"" -DOEMSYSTEMINFOSTRING="\"Samraksh Copyright (C) 2018 Samraksh and Microsoft.\"" -DPLATFORM_ARM_STM32F10x -DPLATFORM_ARM_EmoteDotNow -DTARGETLOCATION_FLASH  -DSAM_APP_TINYCLR  -DLITTLE_ENDIAN -DGCC    -DSAM_STACK_BOTTOM=0x20000000  -DSAM_STACK_TOP=0x20001000  -DSAM_HEAP_BEGIN=0x2000F5AC  -DSAM_HEAP_END=0x20017DF8  -DSAM_CUSTOM_HEAP_BEGIN=0x20017E00  -DSAM_CUSTOM_HEAP_END=0x20017FF8  -DSAM_PROFILER_BUFFER_BEGIN=0x20017F00  -DSAM_PROFILER_BUFFER_END=0x20017FF8 -mfloat-abi=soft -mlittle-endian  -g3 -Og -DSAM_FORCE_GCC_CMDLINE_OPTS -DDEBUG  -D_DEBUG     -I../../Include/DeviceCode -I../../Include/CLR -I../../Include/Support -I../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib -I. -o ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/CLR_RT_InteropAssembliesTable.obj -c ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/CLR_RT_InteropAssembliesTable.cpp
"../../Compilers/GCC5.4.1/bin/arm-none-eabi-ar.exe" -rcs InteropAssembliesTable.lib ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/CLR_RT_InteropAssembliesTable.obj ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/CLR_RT_RuntimeMemory.obj
"../../Compilers/GCC5.4.1/bin/arm-none-eabi-ld.exe"  -static --gc-sections --no-warn-mismatch --library-path=../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/lib --library-path=../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib --allow-multiple-definition -u ARM_Vectors -u _start --Map BuildOutput/Debug/bin/tinyclr.map --output=BuildOutput/Debug/bin/tinyclr.axf --script=tinyclr_scatterfile.ldf ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/tinyclr_dat.obj ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/allocator.obj ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/obj/Solutions/EmoteDotNow/TinyCLR/tinyclr.obj -( ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_Usb_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/InterruptHandler.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/CLRStartup.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_SerialPort.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Xml_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_SerialPort_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Serialization_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Hardware_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_PWM.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/CorLib.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger_full.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Serialization_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Stream.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Diagnostics.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger_extended.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Diagnostics_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/InterruptHandler_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/RPC.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/RPC_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_OneWire.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Hardware.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Serialization.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Messaging.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Messaging_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/WireProtocol.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Graphics_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Messaging_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/I2C.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/I2C_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/IOPort.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/IOPort_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Debugger_minimal.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Update.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/CRC.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_Usb.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Messaging.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/HeapPersistence.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Hardware_PWM_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/HeapPersistence_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SPOT_Serialization.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Xml.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Stream_stub.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/SecurityPkcs11.lib ../../Libs/THUMB2/GCC5.4/le/ANY_MEDIA/Debug/lib/Core.lib ../../Libs/THUMB2/GCC5.4/le/FLASH/Debug/EmoteDotNow/lib/static_tinyclr.lib InteropAssembliesTable.lib  ext.lib -) -( ../../GCCLibs/GCC5.4/newlib/armv7-m/libm.a ../../GCCLibs/GCC5.4/newlib/armv7-m/libc.a ../../Compilers/GCC5.4.1/lib/gcc/arm-none-eabi/5.4.1/armv7-m/libgcc.a -) -(  -)
/bin/sh: 1: Syntax error: "(" unexpected
Makefile:82: recipe for target 'linker' failed
make: *** [linker] Error 2`

**Comment by mukundansridharan** [comment] 2018-08-20 15:40
Thats not the issue, one or more of the files supplied to the linker is missing, Let me check out the repo on a different machine.

**Comment by mukundansridharan** [comment] 2018-08-20 22:00
ok. Nailed down the error. its a weird error where  "(" that needs a \ on one mingw32 but does not need the \ on another. This is caused by the verision of make used. Versions above 4 need the "\". Fixed the makefile to use \, hence GNU make version above 4 will be needed for compiling. Updated the readme with instructions to find make version 4.2.1. Closing the issue.

**Closed as completed by mukundansridharan** 2018-08-20 22:00 UTC
